### ISSUE TITLE
Cardiovascular Heart Disease Prediction | 3. Feature Importance

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#101]
### Is your feature request related to a problem? Please describe.

explore which features pose the most significance in finding the solution. 

### Describe the solution you'd like

Explore both statistical and ML based tests. First list down the algos you will be proceeding with in both categories and then we shall proceed.
@deedGhost 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kaishwarya24** [comment]
please assign me this issue

**Comment by DeepikaMunimadagu** [comment]
Please assign this issue to me. I would like to contribute

**Comment by deedGhost** [comment]
@SrijanShovit For statistical based, I'll be using correlation coefficients and chi-square test and for the ml based I can use random forest or PCA based algos.
