### ISSUE TITLE
[Feature]: Malaria Detection In Human Body Using Body Cell Images

### ISSUE THREAD

**Issue by seeratfatima19** [SrijanShovit/HealthLearning#103]
### Is your feature request related to a problem? Please describe.

Hi @SrijanShovit 

I propose to add the model of Malaria Detection using the dataset of images of human body cells.  
I'll use deep learning model to get to the objective and achieve high accuracy and precision. I have already done work in ML domain so I am experienced to work with NumPy, Pandas, TensorFlow frameworks.

Kindly assign me the issue under the label of GSSoC'24

thanks and regards

### Describe the solution you'd like

I'll get the Cell images dataset from Kaggle and use Pandas for most preprocessing and then leverage TensorFlow for classification of images.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SrijanShovit** [comment]
Dataset link?

**Comment by seeratfatima19** [comment]
Here is the dataset link:
https://www.kaggle.com/datasets/iarunava/cell-images-for-detecting-malaria

**Comment by SrijanShovit** [comment]
Explore some research papers about it. If you can beat them, it's great, otherwise we can only proceed till a nice college project.

**Comment by seeratfatima19** [comment]
Okay so what you mean is if I can beat research papers only then I will be assigned this issue?

**Comment by SrijanShovit** [comment]
No. 
Case 1: You can beat research papers, then superb bcz this dataset saturates around 97%. You can propose this to conferences. It will be a great addition to you profile when you sit in interviews.
Case 2: You couldn't, then it's just a fantastic ml project of college with web ui.

It's a good challenge if you challenge this dataset, keeping in mind light models for web apps. Just telling by my experience with the dataset.

**Comment by seeratfatima19** [comment]
I got you. So please assign me the issue and then when I start working on it, I'll keep experimenting any way I can get its accuracy better than currently existing methods or not.

**Comment by SrijanShovit** [comment]
Go through this discussion on what kind of workflow I expect: https://github.com/SrijanShovit/HealthLearning/pull/56

**Comment by seeratfatima19** [comment]
Yes sure I'll follow the required workflow.

**Comment by seeratfatima19** [comment]
@SrijanShovit I just needed to clarify one thing:
as per the workflow you mentioned, should i open separate issues for 
-> preprocessing
-> model making and evaluation.

**Comment by SrijanShovit** [comment]
1. Since the dataset is balanced and large enough, I don't think there is need for any preprocessing.
2. But you might like to do augmentation and create your version of data and train on that, not on original one. 

Proceed with 1, in case we don't succeed, we can take path 2, for which I will create separate issue.
