### ISSUE TITLE
Covid -19 prediction

### ISSUE THREAD

**Issue by kRiShNa-429407** [SrijanShovit/HealthLearning#105]
**Is your feature request related to a problem? Please describe.**
Coronavirus is a family of viruses that are named after their spiky crown. The novel coronavirus, also known as SARS-CoV-2, is a contagious respiratory virus that first reported in Wuhan, China. On 2/11/2020, the World Health Organization designated the name COVID-19 for the disease caused by the novel coronavirus

**Describe the solution you'd like**
The project  aims at exploring COVID-19 through data analysis and projections.

**Describe alternatives you've considered**

**Additional context**
Coronavirus Case Data is provided by [Johns Hopkins University](https://github.com/CSSEGISandData/COVID-19)

What problem is this feature trying to solve?
Predict covid -19 

How do we know when the feature is complete?

**Comment by SrijanShovit** [comment]
Come on man @kRiShNa-429407 Corona Virus has gone now; it was a good choice in 2020, but not today. Rather chose some disease that is not easily curable or detectable but can affect any person any time at any age.

**Comment by kRiShNa-429407** [comment]
Sure😜
