### ISSUE TITLE
Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [SrijanShovit/HealthLearning#107]
**Is your feature request related to a problem? Please describe.**
Over time, open pull requests (PRs) can accumulate in a repository, cluttering the interface and making it difficult to focus on active development tasks. Additionally, outdated or abandoned PRs may no longer serve their intended purpose and should be closed to maintain repository cleanliness.

**Describe the solution you'd like**
Implement a workflow that automatically closes old PRs based on predefined criteria, such as their last update timestamp. By regularly closing PRs that have not been updated within a certain timeframe, the repository can stay organized, and contributors can focus on active and relevant PRs.

**What problem is this feature trying to solve?**
This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

**Comment by Asymtode712** [comment]
@SrijanShovit Please assign me this issue under gssoc'24

**Comment by SrijanShovit** [comment]
@Asymtode712 I want a condition if there is no comment from my side for 7 days, it will be closed automatically. Is that possible?

**Comment by Asymtode712** [comment]
@SrijanShovit So most of the repos have a threshold time span of 30 days for holding a particular PR but if you want to change it to mere 7 days, I can do that change

**Comment by SrijanShovit** [comment]
sure go ahead @Asymtode712
