### ISSUE TITLE
Maternal Health Risk prediction

### ISSUE THREAD

**Issue by Disha-16** [SrijanShovit/HealthLearning#11]
Hi, I am Disha Mukhopadhyay, currently persuing BTech in Computer Science and Engineering (CSE). I have done an internship as an AI intern. and published an IEEE paper in Machine Learning domain, and also have some papers in proceeding in Machine Learning and data science domain. It will be very helpful if you could assign me this project for GSSOC'24 as a contributor, so that I can work on this project.
Approach for this Project :
1.Data collection and preprocessing: In this section, we will collect and gather the dataset, and preprocess it 
2.Exploratory Data Analysis(EDA): Visual inspection, statistical summary, data distribution will be performed.
3.Model Selection and Deployment: 4 types of machine learning models(XGBoost, Logistic regression Random Forest, gaussian naive Bayes) will be chosen and implemented.
4.Model Training and evaluation: Each model will be trained on the dataset, and performance of each model will be displayed.
5.Model Comparison and Selection: Will analyze the performance of all models based on the metrics obtained and will Choose the model that shows the best balance between accuracy, generalizability, and computational efficiency.
Thank You

**Comment by SrijanShovit** [comment]
Hi @Disha-16 Good to see you approach to the project. I would like to add steps like Feature Importance as well to point out the most critical factors. There are several techniques for that. Moreover, I feel it's better to have multiple issues as steps open for this project. Just wait for sometime, I will be opening several issues.
Hope you enjoy the project and yeah, you can start communicating via Discord #Health Learning channel if that's visible to you.

**Comment by SrijanShovit** [comment]
You can start form here:
https://github.com/SrijanShovit/HealthLearning/issues/13
https://github.com/SrijanShovit/HealthLearning/issues/14

**Comment by Disha-16** [comment]
@SrijanShovit okay, I would love to start from #13 and then i will do the EDA part from #14 . Thank  you for giving me this project
