### ISSUE TITLE
Cirrhosis | 3. Feature Importance

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#115]
### Is your feature request related to a problem? Please describe.

explore which features pose the most significance in finding the solution.

### Describe the solution you'd like

Explore both statistical and ML based tests. First list down the algos you will be proceeding with in both categories and then we shall proceed. @aditi1807 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oj1o1** [comment]
Hey @SrijanShovit I'll add Feature importance . 
Also, Work on Prediction with 4 different M.L using
1)RANDOM FOREST
2)LOGISTIC REGRESSION
3)KNEIGHBORSCLASSIFIER
4)ModelBagging
Can you please assign me this issue ?

**Comment by SrijanShovit** [comment]
@oj1o1 @aditi1807 will proceed with this; i will allot you some other issue or project.
