### ISSUE TITLE
Diabetes Classification| Feature Importance

### ISSUE THREAD

**Issue by Anuragsarkar12** [SrijanShovit/HealthLearning#119]
Hey @SrijanShovit , I am moving ahead with the feature election as you mentioned yesterday, can you assign this issue to me ?

**Comment by SrijanShovit** [comment]
> Hey @SrijanShovit , I am moving ahead with the feature election as you mentioned yesterday, can you assign this issue to me ?

Its feature Selection not election

**Comment by SrijanShovit** [comment]
> > Hey @SrijanShovit , I am moving ahead with the feature election as you mentioned yesterday, can you assign this issue to me ?
> 
> Its feature Selection not election

Can you contact me on discord or linkedin as well

**Comment by Anuragsarkar12** [comment]
Yeah, I'll reach out to you on discord and LinkedIn, sorry for the typo 😅

**Comment by Anuragsarkar12** [comment]
I have made a pull request on this particular issue, from where can I get
your discord ID, I have contacted you on Linkedin .
I had a doubt regarding the point allocation, in my first pr i didn't mark
done for  the following four criteria:

   -  I have performed a self-review of my code
   -  I have commented my code, particularly in hard-to-understand areas
   -  My changes generate no new warnings
   -  I am working on this issue under GSSOC
   - was I assigned points for that particular PR that was merged?

**Comment by Anuragsarkar12** [comment]
I closed the previous pull request  as I had to edit my code  and have made another

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.
