### ISSUE TITLE
Maternal Health Risk Prediction | 1. Explore Dataset

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#13]
**Step 1**

1. Load the dataset
2. Explore and confirm features and label(s) of this dataset
3. Explore size/shape of dataset
4. Investigate data type of features and labels and chose any better option for a particular column for data type if possible
5. Calculate the memory usage differences
6. Explore the statistical facts like mean, median, x percentiles of the columns

**Comment by Arihant-Bhandari** [comment]
Hi @SrijanShovit , can you please assign this to me, i would be glad to contribute in this project.

**Comment by Basma2423** [comment]
Wanna give it a try, can you assign it to me? @SrijanShovit 

Full name: **Basma Mahmoud**
GitHub Profile Link: [Basma2423](https://github.com/Basma2423)
Email ID: mayarbasma2423@gmail.com
Approach for this Project: Use Multiple functions in panda and other libraries to explore the dataset
What is your participant role? (Mention the Open Source program): **GSSoC-2024** participant

Thanks.

**Comment by SrijanShovit** [comment]
Hi @Basma2423 @Arihant-Bhandari @Disha-16 has already expressed her interest to work with this as per https://github.com/SrijanShovit/HealthLearning/issues/11.

@Arihant-Bhandari I will assign you with Metabolic Syndrome Prediction as you expressed interest for that first.
You can express your willingness for a different project which is free.

**Comment by Arihant-Bhandari** [comment]
@SrijanShovit thank you, i would be glad taking up Metabolic Syndrome Prediction problem.

**Comment by Disha-16** [comment]
@SrijanShovit thank you

**Comment by SrijanShovit** [comment]
Hey @Disha-16 How's the progress? Anything to discuss, stuck anywhere?

**Comment by Disha-16** [comment]
@SrijanShovit It's almost done, Just doing some last min touch-up

**Comment by SrijanShovit** [comment]
Ok

**Comment by SrijanShovit** [comment]
> @SrijanShovit It's almost done, Just doing some last min touch-up

Hi; would you able or willing to complete the issue? Can I have some clarity about this; whatever be the situation with you; I need to know atleast.

**Comment by SrijanShovit** [comment]
> > @SrijanShovit It's almost done, Just doing some last min touch-up
> 
> Hi; would you able or willing to complete the issue? Can I have some clarity about this; whatever be the situation with you; I need to know atleast.

Else I shall re-assign this.

**Comment by Disha-16** [comment]
added csv and dataset exploration file #94
I have made the PR assigned to me
