### ISSUE TITLE
Cataract Eye Disease Prediction 

### ISSUE THREAD

**Issue by saikrishna823** [SrijanShovit/HealthLearning#133]
### Is your feature request related to a problem? Please describe.

Dataset:https://www.kaggle.com/datasets/andrewmvd/ocular-disease-recognition-odir5k
The above dataset can used to identify for lot of eye disease.But I will be focusing on cataract disease.As we all know that cataract is  one of the eye disease that usually occurs to ageing people .It leads to clouding of the 

### Describe the solution you'd like

So to identify this I will be designing a deep learning model that can identify the disease.First I will construct a CNN model ,then I will use some pretrained models like Resnet,VGG for better performance.I will be using accuracy, precision as evaluation metrics.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SrijanShovit** [comment]
I need a model less than 5 MB. So what would be the plan?

**Comment by saikrishna823** [comment]
I will use pretrained models like MobileNetV2 , Efficient Net,which are more performant and less in size.

**Comment by SrijanShovit** [comment]
@saikrishna823 I hope you are aware of the flows of an ML project at my repo.
