### ISSUE TITLE
[Project Addition]: Brain Tumor Segmentation

### ISSUE THREAD

**Issue by Karthik110505** [SrijanShovit/HealthLearning#135]
🔴 Project Title : Brain Tumor Segmentation

🔴 Aim : To Segment the tumor in brain

🔴 Dataset :https://www.kaggle.com/datasets/nikhilroxtomar/brain-tumor-segmentation?select=masks

🔴 Approach : Use the pretrained models like variants of yolo inorder to segment the brain tumor .

@SrijanShovit  Please assign me this issue

**Comment by SrijanShovit** [comment]
What all steps would you apply. Provide a detailed roadmap(including optim, act functions, metrics,etc)

**Comment by Karthik110505** [comment]
# Process that I follow:

- Download the dataset from kaggle

- Inspect the data and prepare it for model training

- Try downloading yolo varients like yolov8 , yolov7, yolov5 and train the model.

- Evaluate the model performance and modify the parameters for better model performance

- Choose the best performing model

- Predict the brain tumor in testing dataset
 
- The output consist of images with segmentation  around the brain tumor.
Note: Currently I can't mention the optm, act and metrics . As we can't tell the perfect one's before the model training. They vary with data that we take 

@SrijanShovit
