### ISSUE TITLE
Maternal Health Risk Prediction | 2. EDA

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#14]
**Step 2:**

1. Perform Univariate and Multivariate analysis and draw conclusions from there.
2. Explore Correlation Matrix(can try different methods and search if they give the same conclusion and why)
3. Check the distribution(skewness) of the columns
4. Detect Outliers(don't remove)
5. Detect Class Label Imbalance

Provide as much relevant graphs and conclusive markdown cells as possible.

**Comment by Basma2423** [comment]
Wanna give it a try, can you assign it to me? @SrijanShovit 

Full name: **Basma Mahmoud**
GitHub Profile Link: [Basma2423](https://github.com/Basma2423)
Email ID: mayarbasma2423@gmail.coma
Approach for this Project: multiple EDA techniques
What is your participant role? (Mention the Open Source program): **GSSoC**-2024 participant

Can you add the label for **GSSoC**, please?
Thanks.

**Comment by SrijanShovit** [comment]
@Disha-16

**Comment by SrijanShovit** [comment]
Hi @Basma2423 @Disha-16 has already expressed her interest to work with this as per https://github.com/SrijanShovit/HealthLearning/issues/11.

You can express your willingness for a different project which is free.

**Comment by Disha-16** [comment]
@SrijanShovit I will do my best to execute this project

**Comment by Disha-16** [comment]
hi @SrijanShovit 
EDA of Maternal Health Risk Prediction #102
I have made the PR assigned to me
