### ISSUE TITLE
Chest X-rays: Pneumonia Detection | 1. Dataset Preparation

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#15]
Step 1:

1. Add relevant folder with readme in the repo
2. Can explore datasets; btw we can start with https://www.kaggle.com/datasets/paultimothymooney/chest-xray-pneumonia
3. Explore classes and their respective sizes in dataset and perform necessary augmentation.
4. Decide upon the number of samples nearly for each class and relevant strategy for noise removal,augmentation(be careful about this).
5. Upload augmented dataset on kaggle(easy to work with later).

These all steps make us ready to start working on a proper dataset.

**Comment by Basma2423** [comment]
I'm in, can you assign it to me? @SrijanShovit 

Full name: **Basma Mahmoud**
GitHub Profile Link: [Basma2423](https://github.com/Basma2423)
Email ID: mayarbasma2423@gmail.com
Approach for this Project: Multiple Deep Learning pre-trained models + CNN
What is your participant role? (Mention the Open Source program): **GSSoC-2024** participant

Can you add the label for **GSSoC**, please?
Thanks.

**Comment by SrijanShovit** [comment]
@roysammy123 Please proceed

**Comment by roysammy** [comment]
sure, will get started with this right away! thanks for assigning this to me @SrijanShovit

**Comment by SrijanShovit** [comment]
What's the progress @roysammy123 ?

**Comment by roysammy** [comment]
Have started working on it, will finish it by this week @SrijanShovit

**Comment by SrijanShovit** [comment]
This step is for dataset prep. I hope you are not working till the end step for now. Those will be different issues.

**Comment by roysammy** [comment]
Yeah yeah I am aware, just working on preparing the data now

**Comment by SrijanShovit** [comment]
What's the progress @roysammy123

**Comment by roysammy** [comment]
Have raised a PR. Please check and merge @SrijanShovit
