### ISSUE TITLE
Parkinson's Disease Detection | Dataset Exploration & EDA

### ISSUE THREAD

**Issue by ranamanish674zu** [SrijanShovit/HealthLearning#150]
Is your feature request related to a problem? Please describe.
Parkinson’s disease (PD) is a chronic and progressive neurological disorder that affects muscle movement, leading to symptoms such as tremors, rigidity, bradykinesia (slowness of movement), and postural instability. Early detection of PD is crucial for effective management and treatment, which can significantly improve the quality of life for patients. Traditional diagnostic methods, such as clinical evaluations and imaging techniques, can be costly, invasive, and not always accessible, especially in remote areas. Consequently, there is a need for a more accessible, non-invasive, and cost-effective method for early detection of Parkinson's disease.

Describe the solution you'd like
The solution involves developing a machine learning model that can detect Parkinson’s disease using non-invasive data inputs. 
Describe alternatives you've considered
Several alternative solutions have been considered:

Traditional Diagnostic Methods: Techniques such as PET scans and MRI are accurate but expensive and invasive, making them impractical for routine screening.
Clinical Evaluations: Regular check-ups with neurologists can be effective but are not always feasible for all patients due to geographic and financial constraints.
Symptom Tracking Apps: Mobile applications that track symptoms reported by patients can provide useful data but are subjective and may lack the precision of sensor-based data.
Additional context
In developing this solution, it's important to consider:

Data Collection: A large and diverse dataset is essential for training a robust machine learning model. Data should be collected from different demographics and disease stages.
Integration with Healthcare Systems: The diagnostic tool should be designed for easy integration with existing healthcare IT systems to facilitate adoption by clinics and hospitals.
User-friendly Interface: Both patients and healthcare providers should find the tool easy to use, ensuring widespread acceptance and regular usage.
What problem is this feature trying to solve?
This feature aims to solve the problem of late and inaccessible diagnosis of Parkinson’s disease. By providing a non-invasive, cost-effective, and easily accessible diagnostic tool, it enables early detection and intervention, which can slow disease progression and improve patient outcomes. The tool also addresses the limitations of traditional diagnostic methods and ensures more frequent monitoring of at-risk individuals.

How do we know when the feature is complete?
The feature will be considered complete when it meets the following criteria:

Accuracy and Reliability: The machine learning model consistently achieves high accuracy in detecting Parkinson's disease across diverse patient data.
Clinical Validation: The tool has been validated through clinical trials and has received approval from relevant medical authorities.
User Adoption: Healthcare providers have integrated the tool into their practice, and patients are using it regularly for screenings.
Positive Outcomes: There is measurable evidence of improved patient outcomes, including earlier diagnosis, more effective treatment plans, and enhanced quality of life for patients.
![image](https://github.com/SrijanShovit/HealthLearning/assets/119676300/8d80fe33-68ac-47e5-8b40-0b2178cf7566)
![image](https://github.com/SrijanShovit/HealthLearning/assets/119676300/5fd704dc-cf44-4288-b557-0a9acd3add2a)

**Comment by ranamanish674zu** [comment]
@SrijanShovit if possible assign it to me i want to work on it

**Comment by SrijanShovit** [comment]
Lots of things written but missed basic thing. Which dataset?

**Comment by ranamanish674zu** [comment]
ahh Sorrry....the data set is named as -parkinsondisease.csv which is available on - https://www.kaggle.com/datasets/vikasukani/parkinsons-disease-data-set
or at - https://archive.ics.uci.edu/dataset/189/parkinsons+telemonitoring
which contains this attributesd-
sex-male,female
name: Subject name or identifier.
MDVP
(Hz): Average vocal fundamental frequency.
MDVP
(Hz): Maximum vocal fundamental frequency.
MDVP
(Hz): Minimum vocal fundamental frequency.
MDVP
(%), MDVP
(Abs): Measures of variation in fundamental frequency.
MDVP
: Relative amplitude perturbation.
MDVP
: Five-point period perturbation quotient.
Jitter
: Average absolute difference of differences between consecutive periods.
MDVP
: Measures of variation in amplitude.
MDVP
(dB): Another measure of variation in amplitude (in decibels).
Shimmer
: Three-point amplitude perturbation quotient.
Shimmer
: Five-point amplitude perturbation quotient.
MDVP
: Eleven-point amplitude perturbation quotient.
Shimmer
: Average absolute difference of differences between consecutive amplitudes.
NHR: Noise-to-harmonics ratio.
HNR: Harmonics-to-noise ratio.
RPDE: Recurrence period density entropy.
DFA: Detrended fluctuation analysis.
spread1: Nonlinear measure of fundamental frequency variation.
spread2: Nonlinear measure of fundamental frequency variation.
D2: Correlation dimension.
PPE: Pitch period entropy.
status: Health status of the subject (1 - Parkinson's disease, 0 - healthy).

**Comment by SrijanShovit** [comment]
Before I assign you this, can you have a look on the desired workflows for an ML project? You can refer issues related to metabolic syndrome.

**Comment by ranamanish674zu** [comment]
yes sir....actually i have seen workflow , that can be (it can be change according the condition but most probably it will)-
1.Importing Libraries and Dataset
2. data pre-processing -cleaning(removing nulls ) , statistical analysis -mean , mediun,mode,max,min......etc
3. Exploratory Data Analysis (EDA)-hypothesis testing can be done or chi-square tests
4. can drop some of feature which will be not useful 
5. Model Training(diff types of ml model if needed we can go with the deep learning model which will be accurate)
6. Model evaluation(like confusion matrix ,accuracy ,precision , recalll , f1-score.....etc
7. Interpretation and Insights

**Comment by SrijanShovit** [comment]
Ok go ahead with Dataset Exploration and EDA part.

**Comment by ranamanish674zu** [comment]
@SrijanShovit done #150 could you please evaluate it ?
