### ISSUE TITLE
diabetesclassification (Using Machine Learning algorithm)

### ISSUE THREAD

**Issue by ranamanish674zu** [SrijanShovit/HealthLearning#152]
### Describe the bug

The bug in the diabetes classification pipeline is the lack of model training after completing exploratory data analysis (EDA) and preprocessing steps. Without model training, the system cannot learn from the processed data to make accurate predictions.

### Expected behaviour

Following EDA and preprocessing, I expected the implementation of a machine learning algorithm for diabetes classification. This would involve training the model on the preprocessed data to learn patterns and relationships, ultimately enabling it to accurately classify instances of diabetes based on input features.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SrijanShovit** [comment]
Have you tried communicating with PA whether he has something aligned or not before categorizing this as a "bug" and "invalid"?
