### ISSUE TITLE
Stroke Prediction | Feature Importance

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#154]

**Comment by Garvitjoshi1** [comment]
Hello @SrijanShovit Sir, Kindly assign this task to me. As I have done a project regarding this already so I can complete this issue well.

**Comment by SrijanShovit** [comment]
Ok go ahead.

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.

**Comment by Garvitjoshi1** [comment]
@SrijanShovit sir, have completed it and have created a pull request for the same  named as Feature Importance.
