### ISSUE TITLE
Stroke Prediction | 1. Explore Dataset

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#16]
Step 1

1. Load the dataset
2. Explore and confirm features and label(s) of this dataset
3. Explore size/shape of dataset
4. Investigate data type of features and labels and chose any better option for a particular column for data type if possible
5. Calculate the memory usage differences
6. Explore the statistical facts like mean, median, x percentiles of the columns

@Divyanshi1002 Please proceed.

**Comment by Divyanshi1002** [comment]
sure sir, please assign me the issue.

**Comment by yusuf-khaan** [comment]
Hey @SrijanShovit can you assign this issue to me i would be glad to be a part of it,  Previously i have worked with with various exploration of datasets and have good experience in it

**Comment by Pookie-n-Rookie** [comment]
Hey @SrijanShovit can you assign this issue to me i want to be a part of it. I wanna learn more and apply data exploration
