### ISSUE TITLE
Knee Osteoarthritis Prediction

### ISSUE THREAD

**Issue by devarshh08** [SrijanShovit/HealthLearning#168]
### Is your feature request related to a problem? Please describe.

Knee Osteoarthritis is a problem very common among the population of today. It is more common in females above the age of 40. There are many factors which play a role in that, but it can be predicted early in age considering a few things.

### Describe the solution you'd like along with reference dataset.

Aim : Classifying images of x-rays into chances of the patient getting osteoarthritis also keeping the other factors in mind as well such as gender and age.

Dataset : https://www.kaggle.com/datasets/shashwatwork/knee-osteoarthritis-dataset-with-severity/data

### Additional context

This is inspired by the brain tumor prediction and parkinson's prediction and likewise projects.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SrijanShovit** [comment]
Go ahead but first get acquainted with the requirements of DL project from PR discussions of MRI classification.

**Comment by devarshh08** [comment]
@SrijanShovit Definitely I will!
Thank you very much!

**Comment by devarshh08** [comment]
Hi @SrijanShovit, I want to request a few days extension for completing this project. Because it is my first time I am facing a lot of issues and am working to resolve them.

Thank you very much for understanding.
