### ISSUE TITLE
Stroke Prediction | 2. EDA

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#17]
**Step 2:**

1. Perform Univariate and Multivariate analysis and draw conclusions from there.
2. Explore Correlation Matrix(can try different methods and search if they give the same conclusion and why)
3. Check the distribution(skewness) of the columns
4. Detect Outliers(don't remove)
5. Detect Class Label Imbalance

Provide as much relevant graphs and conclusive markdown cells as possible.

Once finished https://github.com/SrijanShovit/HealthLearning/issues/16, proceed with this @Divyanshi1002

**Comment by Divyanshi1002** [comment]
sure, sir.

**Comment by Sayeda-fatima** [comment]
Hi, I would like to work on the classification part of this dataset. I'm a GSSoC'24 contributor. Please assign me this issue

**Comment by SrijanShovit** [comment]
Hi @Sayeda-fatima  as already things are aligned, you can propose some other disease work. Will approve that.

**Comment by Divyanshi1002** [comment]
Can I further add model creation, after balancing the data?
i am thinking to use XGBoost (Extreme Gradient Boosting) as it handles missing values, and can work with a variety of feature types.
as well as compare it with other model like RF and LR.

**Comment by SrijanShovit** [comment]
No, the next step is feature importance. Then comes the prediction pipeline. Proceed with ML and statistical tests of feature importance. You can create issue yourself.
