### ISSUE TITLE
Pneumonia Detection using Deep Learning

### ISSUE THREAD

**Issue by AadiJain06** [SrijanShovit/HealthLearning#173]
### Is your feature request related to a problem? Please describe.

Pneumonia which is a dangerous disease that may occur in one or both lungs usually caused by viruses, fungi or bacteria. We will detect this lung disease based on the x-rays we have. Chest X-rays dataset is taken from [Kaggle](https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia) which contain various x-rays images differentiated by two categories “Pneumonia” and “Normal”. We will be creating a deep learning model which will actually tell us whether the person is having pneumonia disease or not having pneumonia.

Assign this issue under GSSOC'24

### Describe the solution you'd like along with reference dataset.

VGG16: It is an easy and broadly used Convolutional Neural Network (CNN) Architecture used for ImageNet which is a huge visible database mission utilized in visual object recognition software research.

Transfer learning (TL): It is a technique in deep learning that focuses on taking a pre-trained neural network and storing knowledge gained while solving one problem and applying it to new different datasets. In this article, knowledge gained while learning to recognize 1000 different classes in ImageNet could apply when trying to recognize the disease.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adityasingh-0803** [comment]
Kindly assign the issue i can do it
