### ISSUE TITLE
Rock Mine prediction 

### ISSUE THREAD

**Issue by anurag6569201** [SrijanShovit/HealthLearning#174]
Hello admin ,

I wanted to add rock mine prediction which will use the Kaggle dataset of rock mine it consists of 60 features and 208 datapoints which is quite good for the machine learning using the logistic regression the accuracy comes around 85%.
I have decided to use cross validation method so that accuracy can be improved.

## Please assign me !!

**Comment by SrijanShovit** [comment]
@anurag6569201 since when did rock mine prediction become part of human health?
