### ISSUE TITLE
Infant Health Prediction | 1. Explore Dataset

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#18]
Step 1

1. Load the dataset
2. Explore and confirm features and label(s) of this dataset
3. Explore size/shape of dataset
4. Investigate data type of features and labels and chose any better option for a particular column for data type if possible
5. Calculate the memory usage differences
6. Explore the statistical facts like mean, median, x percentiles of the columns

@Basma2423 Please proceed.

**Comment by Basma2423** [comment]
@SrijanShovit 
Sure thing, thank you 🫡
