### ISSUE TITLE
Infant Health Prediction | 2. EDA

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#19]
**Step 2:**

1. Perform Univariate and Multivariate analysis and draw conclusions from there.
2. Explore Correlation Matrix(can try different methods and search if they give the same conclusion and why)
3. Check the distribution(skewness) of the columns
4. Detect Outliers(don't remove)
5. Detect Class Label Imbalance

Provide as much relevant graphs and conclusive markdown cells as possible.

**Comment by yusuf-khaan** [comment]
Hey @SrijanShovit can you assign this issue to me, i would be glad to contribute to it  and I have compatible skills and experience to perform EDA on this issue

**Comment by SrijanShovit** [comment]
ok @yusuf-khaan Proceed

**Comment by yusuf-khaan** [comment]
Thanks for giving me this opportunity

**Comment by yusuf-khaan** [comment]
hey @SrijanShovit , i was wondering if it is possible to get assigned more than one issue if the contestant feel capable?

**Comment by SrijanShovit** [comment]
I will do that when we get mentors bcz alone, it's getting difficult to manage. So, rn I'm only restricting to 1 project/issue per user.
