### ISSUE TITLE
Anxiety Depression detection

### ISSUE THREAD

**Issue by adityasingh-0803** [SrijanShovit/HealthLearning#191]
We can create anxiety detection.
Please assign me under suitable labels  @SrijanShovit

**Comment by adityasingh-0803** [comment]
@SrijanShovit any update?

**Comment by khushi57** [comment]
> We can create anxiety detection. Please assign me under suitable labels @SrijanShovit
I WOULD LIKE TO WORK ON THIS PROJECT. PLEASE ASSIGN IT TO ME.

**Comment by adityasingh-0803** [comment]
@SrijanShovit please see
