### ISSUE TITLE
Understanding the importance of Mental Health in Workplace: EDA and analysis

### ISSUE THREAD

**Issue by Nidhi-Satyapriya** [SrijanShovit/HealthLearning#193]
### Is your feature request related to a problem? Please describe.

Importance of Understanding Mental Health in Tech:
1) Stigma Reduction: Promotes awareness and encourages open discussions, fostering a supportive workplace culture.
2) Legal and Ethical Considerations: Understanding employee needs can ensure compliance and foster ethical practices.
3) Work-Life Balance: Identifying factors that affect work-life balance helps in creating a healthier work environment.

### Describe the solution you'd like along with reference dataset.

Data Collection: from kaggle datasets-(https://www.kaggle.com/datasets/thedevastator/mental-health-in-tech-survey)
Data Cleaning
Exploratory Data Analysis (EDA)
Feature Engineering
Data Modeling- 
Model Evaluation
Visualization and Recommendations:
Deployment

### Describe alternatives you've considered

Using deep learning models can enhance the depth of analysis, providing more nuanced insights into mental health in the tech industry. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nidhi-Satyapriya** [comment]
@SrijanShovit kindly assign this issue to me.

**Comment by Nidhi-Satyapriya** [comment]
hey @SrijanShovit sir, did you find this useful?
In HealthLearning, I thought it's equally crucial for people and workspaces to be aware of the mental care needs of the employee.
This dataset can give great insight into, to name a few:-
1) Understanding the extent to which mental health issues affect job performance and productivity.
2) The availability and effectiveness of mental health support in the workplace and its impact on employee well-being.
Kindly let me know if I can proceed with this issue.

**Comment by Nidhi-Satyapriya** [comment]
@SrijanShovit @sanjay-kv sir, the issues are getting staled and closed. It would be better if you looked at this once and offer your advise, whether positive or negative.

**Comment by sanjay-kv** [comment]
This aint my repo, as a PM I can only help with changing labels, but indeed can alert admin about this via email.

**Comment by Nidhi-Satyapriya** [comment]
kindly do sir..
