### ISSUE TITLE
Body Fat Prediction | Distribution Exploration

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#2]
Check if the features have normal distribution or some other distributions. What can be the impact of this on ML models? 
What remedies can be there to solve any possible issues?

**Comment by oj1o1** [comment]
Hey @SrijanShovit 
I'll check it using different classifiers like naive bayes , SVC etc. Also i would like to perform chi-square test and different different plots using seaborn ... please assign this task to me

**Comment by ghost** [comment]
"I'll take responsibility for handling this task. My plan involves assessing the proposed solution using various classifiers such as Naive Bayes, SVC, etc. Additionally, I aim to conduct a chi-square test and generate different plots using Seaborn.

Key tasks include:

1.Evaluating the proposed solution using classifiers like Naive Bayes, SVC, etc.
2.Conducting a chi-square test to assess the significance of the results.
3.Generating different plots using Seaborn to visualize the data and findings.

**Comment by SrijanShovit** [comment]
Hi @oj1o1 You please proceed with this and explore plots as well for pointing out the nature of distribution of the feature. I will assign it to you tomorrow. 

@PriyanshuShankar I will assign a similar issue of different subject to you in the evening. By that time, you can start exploring other datasets or can open an issue where you want to work.

**Comment by Piyushseth55** [comment]
Hii @SrijanShovit, I am Piyush. Under GSSOC'24, I would like to work on this issue. Please assign me this!! #gssoc24

**Comment by oj1o1** [comment]
Hey @SrijanShovit Assign me asap please

**Comment by SrijanShovit** [comment]
> Hey @SrijanShovit Assign me asap please

https://github.com/SrijanShovit/HealthLearning/issues/21#issuecomment-2105578551
