### ISSUE TITLE
Metabolic Syndrome Prediction | 2. EDA

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#20]
**Step 2:**

1. Perform Univariate and Multivariate analysis and draw conclusions from there.
2. Explore Correlation Matrix(can try different methods and search if they give the same conclusion and why)
3. Check the distribution(skewness) of the columns
4. Detect Outliers(don't remove)
5. Detect Class Label Imbalance

Provide as much relevant graphs and conclusive markdown cells as possible.
after https://github.com/SrijanShovit/HealthLearning/issues/5, proceed here @Arihant-Bhandari

**Comment by SanjanaBankar** [comment]
Hello @SrijanShovit,

I believe I can take on the task of performing the exploratory data analysis (EDA) for the Health Learning project. With my previous experience in EDA, I understand the importance of thorough analysis in uncovering insights and informing subsequent steps.

I'll ensure to provide clear and informative visualizations along with conclusive markdown cells to effectively communicate our findings and recommendations.

Looking forward to contributing to the Health Learning project! 

Best regards,
Sanjana

**Comment by SrijanShovit** [comment]
Hi @SanjanaBankar  I have already decided to assign it to  @Arihant-Bhandari, so you can comment on any other project whose EDA part has not been allotted by me in comments. 
Else, I can provide you with issues of Feature Importance.

**Comment by SanjanaBankar** [comment]
> Hi @SanjanaBankar I have already decided to assign it to @Arihant-Bhandari, so you can comment on any other project whose EDA part has not been allotted by me in comments. Else, I can provide you with issues of Feature Importance.

Hello @SrijanShovit 
Thank you for your update! After reviewing other issues, every issue has been assigned. If there are any other aspects of the project that require attention or if there are additional tasks that need to be addressed, please feel free to assign them to me.

**Comment by Arihant-Bhandari** [comment]
@SrijanShovit hi Srijan, i was hoping to get your opinion on this : would it be okay if i were to send multiple commits for different steps so that you can guide me if i am working on the right path ? that would be immensely helpful since i would be rooted towards the given problems , and help me fix things if they arise.

**Comment by SrijanShovit** [comment]
> @SrijanShovit hi Srijan, i was hoping to get your opinion on this : would it be okay if i were to send multiple commits for different steps so that you can guide me if i am working on the right path ? that would be immensely helpful since i would be rooted towards the given problems , and help me fix things if they arise.

Yupp it works

**Comment by Arihant-Bhandari** [comment]
Hi @SrijanShovit I completed step 2 last night and sent a PR in , can you review and suggest changes if any ?

Thank you for the time.

**Comment by SrijanShovit** [comment]
> Hi @SrijanShovit I completed step 2 last night and sent a PR in , can you review and suggest changes if any ?
> 
> Thank you for the time.

Merged, have a look there.
