### ISSUE TITLE
Cervical cancer prediction

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [SrijanShovit/HealthLearning#200]
### Is your feature request related to a problem? Please describe.

It is used to predict user which have disease like cervical cancer 

### Describe the solution you'd like along with reference dataset.

i would like to make a model which predict the cervical cancer .i implement this with following model
1. Logistic Regression
2. Support Vector Classifier (SVC)

dataset taken from kaggle

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nandhinirameshmala** [comment]
Can you assign this issue to me

**Comment by agarwalhimanshugaya** [comment]
Please assign me this issue
