### ISSUE TITLE
Body Fat Prediction | 2. EDA

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#21]
**Step 2:**

1. Detect Outliers(don't remove)
2. Detect Class Label Imbalance

Provide as much relevant graphs and conclusive markdown cells as possible.
Proceed here after https://github.com/SrijanShovit/HealthLearning/issues/1,@sanketv010

**Comment by SrijanShovit** [comment]
@sanketv010 You proceed with step2: 1 and 2

**Comment by SrijanShovit** [comment]
1. Perform Univariate and Multivariate analysis and draw conclusions from there.
2. Explore Correlation Matrix(can try different methods and search if they give the same conclusion and why)
3. Check the distribution(skewness) of the columns

@oj1o1 Please proceed with these 3

**Comment by RutikaW1155** [comment]
Hello , I am GSSOC'24 contributor. 
Can you please assign this issue as I have worked on a similar problem earlier?

**Comment by SrijanShovit** [comment]
Hi @RutikaW1155 , It's already up. If you could point another sub project(disease) whose EDA is not assigned, I will be happy to assign it to you.

**Comment by RutikaW1155** [comment]
Okay, Thank you for your kind response. If there is any issue regarding EDA then please do consider my request.

**Comment by SrijanShovit** [comment]
Noted @RutikaW1155
