### ISSUE TITLE
Body Fat Prediction | 3. Feature Importance | 3.2 Chi-sqaured and/or Anova test

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#25]
Use these tests to again rank the features for their importance contribution towards the label. @MehekFatima (if you want to take up the issue)

**Comment by MehekFatima** [comment]
I'm eager to start working on it. Could you please confirm if it's okay for me to create a new file for this purpose? Alternatively, if there are any other tasks or projects available that align with my skills and interests, I'd be more than happy to contribute to those.

Please let me know your thoughts on how to proceed. @SrijanShovit

**Comment by SrijanShovit** [comment]
Yes, please create folders like PCA-> actual file and analysis readme
Similarly for this issue.

**Comment by MehekFatima** [comment]
okay 👍
