### ISSUE TITLE
Hepatitis C Prediction | 1. Explore Dataset

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#26]
Step 1

1. Load the dataset
2. Explore and confirm features and label(s) of this dataset
3. Explore size/shape of dataset
4. Investigate data type of features and labels and chose any better option for a particular column for data type if possible
5. Calculate the memory usage differences
6. Explore the statistical facts like mean, median, x percentiles of the columns

@SanjanaBankar Please proceed.

**Comment by SanjanaBankar** [comment]
> Step 1
> 
> 1. Load the dataset
> 2. Explore and confirm features and label(s) of this dataset
> 3. Explore size/shape of dataset
> 4. Investigate data type of features and labels and chose any better option for a particular column for data type if possible
> 5. Calculate the memory usage differences
> 6. Explore the statistical facts like mean, median, x percentiles of the columns
> 
> @SanjanaBankar Please proceed.

Yes, I'll Proceed

**Comment by SrijanShovit** [comment]
@SanjanaBankar What's the progress?

**Comment by SanjanaBankar** [comment]
> @SanjanaBankar What's the progress?

Hello, @SrijanShovit 
It's inprogress, will raise the PR by Tomorrow

**Comment by SrijanShovit** [comment]
@SanjanaBankar any progress? Would you continue?

**Comment by SanjanaBankar** [comment]
> @SanjanaBankar any progress? Would you continue?

Yes, apologies for this much delay. We are having our endsemester examinations going on. I'm on it now.
