### ISSUE TITLE
Cirrhosis Prediction | 1. Explore Dataset

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#27]
Step 1

1. Load the dataset
2. Explore and confirm features and label(s) of this dataset
3. Explore size/shape of dataset
4. Investigate data type of features and labels and chose any better option for a particular column for data type if possible
5. Calculate the memory usage differences
6. Explore the statistical facts like mean, median, x percentiles of the columns

@aditi1807 Please proceed if you would like to take it up.

**Comment by aditi1807** [comment]
Sure...

**Comment by aditi1807** [comment]
hey @SrijanShovit  do i have to only proceed till point 6 of step 1 or can i go further

**Comment by SrijanShovit** [comment]
Proceed with listed steps only for this issue, other steps will be covered in separate issue. Once we merge this one, I will assign the next one to you.

**Comment by aditi1807** [comment]
ohk

**Comment by aditi1807** [comment]
done the step 1. do check and let me know if any changes or error occurs

**Comment by aditi1807** [comment]
Hey @SrijanShovit ,
could you please assign me more issues regarding this project since i have already did some work and i am really interested in following this project

**Comment by SrijanShovit** [comment]
> Hey @SrijanShovit , could you please assign me more issues regarding this project since i have already did some work and i am really interested in following this project

Go ahead : https://github.com/SrijanShovit/HealthLearning/issues/57#issue-2291390668
