### ISSUE TITLE
PCOS Detection | 1. Dataset Exploration

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#28]
@Piyushseth55 Would you like to take it up?

Step 1

1. Load the dataset
2. Explore and confirm features and label(s) of this dataset
3. Explore size/shape of dataset
4. Investigate data type of features and labels and chose any better option for a particular column for data type if possible
5. Calculate the memory usage differences
6. Explore the statistical facts like mean, median, x percentiles of the columns

**Comment by Pookie-n-Rookie** [comment]
@SrijanShovit  i am interested . Kindly assign me the issue

**Comment by ghost** [comment]
@SrijanShovit I am Eager to contribute  kindly assign me the issue

**Comment by Piyushseth55** [comment]
> @Piyushseth55 Would you like to take it up?
> 
> Step 1
> 
> 1. Load the dataset
> 2. Explore and confirm features and label(s) of this dataset
> 3. Explore size/shape of dataset
> 4. Investigate data type of features and labels and chose any better option for a particular column for data type if possible
> 5. Calculate the memory usage differences
> 6. Explore the statistical facts like mean, median, x percentiles of the columns

Yes sure

**Comment by Piyushseth55** [comment]
> @Piyushseth55 Would you like to take it up?
> 
> Step 1
> 
> 1. Load the dataset
> 2. Explore and confirm features and label(s) of this dataset
> 3. Explore size/shape of dataset
> 4. Investigate data type of features and labels and chose any better option for a particular column for data type if possible
> 5. Calculate the memory usage differences
> 6. Explore the statistical facts like mean, median, x percentiles of the column.

 It would be great if you assigned me to this issue.

**Comment by Piyushseth55** [comment]
Task completed and I also make the PR. Please check it.

**Comment by SrijanShovit** [comment]
> Task completed and I also make the PR. Please check it.

Merged. Proceed with https://github.com/SrijanShovit/HealthLearning/issues/65

**Comment by SrijanShovit** [comment]
@Piyushseth55  are you working on #65

**Comment by Piyushseth55** [comment]
> @Piyushseth55 are you working on #65

Not yet , please assign me this I will start working on it.
