### ISSUE TITLE
explorative data analysis

### ISSUE THREAD

**Issue by nagamukesh** [SrijanShovit/HealthLearning#30]
I want to add some more modifications to the existing notebooks regarding explorative data analysis such as data normalization, decreasing skewness and trying more models like random forests, naive bayes etc
please assign this issue to me under gssoc 2024
I can contribute to this project

**Comment by SrijanShovit** [comment]
Please specify your desired topic @nagamukesh  just opening issue won't work

**Comment by nagamukesh** [comment]
@SrijanShovit sorry for not mentioning earlier, I would like to work on Metabolic Syndrome by doing some experiments such as removing some outliers,normalizing data and feature extraction etc

**Comment by 1arka02** [comment]
hi @SrijanShovit  i am a gssoc contributor,i want to contribute to this project as well can u assign me some tasks

**Comment by 1arka02** [comment]
i would like to work on data exploration and data analysis part on any mentioned topics

**Comment by SrijanShovit** [comment]
Already being taken, search for a disease instead and propose some idea. I shall approve it.

**Comment by 1arka02** [comment]
I can work on the hepatitis C prediction data set, I want to work on data
exploration,preprocessing and feature engineering
 Can u assign it?
Regards

**Comment by SrijanShovit** [comment]
No, it's already being worked upon.
