### ISSUE TITLE
Breast Cancer Prediction | 1. Dataset Exploration

### ISSUE THREAD

**Issue by vedanshipathak** [SrijanShovit/HealthLearning#38]
@SrijanShovit 
I would like to contribute for the project Breast Cancer Prediction as GSSOC'24 contributor by implementing Logistic Regression model .
Thank you.

**Comment by SrijanShovit** [comment]
ok, so which dataset are you gonna use? I will approve that once we have the dataset.

**Comment by yusuf-khaan** [comment]
Hey @SrijanShovit ,  I would like to work on this issue , I have completed the previous issue and has sent a pull closed to merge it. I have also worked on Breast Cancer Prediction Previously, I believe my experience will be valuable and would gladly love to contribute to it , if You assign it to me

**Comment by SrijanShovit** [comment]
First let @vedanshipathak express her answer. Will decide after that.

**Comment by vedanshipathak** [comment]
@SrijanShovit  i worked on the dataset which is available on kaggle.  i have already done a project on that so i have a good knowledge about that.

**Comment by SrijanShovit** [comment]
Link? Would like to know if it's image dataset or WISCONSIN dataset or any other one?

**Comment by vedanshipathak** [comment]
@SrijanShovit  It's a WISCONSIN dataset .Do you want me to attach the link?

**Comment by SrijanShovit** [comment]
No that's fine. I know the dataset well.
Proceed with the basics. I will frame issues for the next steps.
do add a folder with readme in the project for this disease.

Step 1

1. Load the dataset
2. Explore and confirm features and label(s) of this dataset
3. Explore size/shape of dataset
4. Investigate data type of features and labels and chose any better option for a particular column for data type if possible
5. Calculate the memory usage differences
6. Explore the statistical facts like mean, median, x percentiles of the columns
