### ISSUE TITLE
Stroke Prediction 

### ISSUE THREAD

**Issue by Divyanshi1002** [SrijanShovit/HealthLearning#4]
Hello @SrijanShovit,
I would like to contribute for Stroke Prediction under GSSOC'24, by implementing the following methods for Stroke prediction:

**Logistic Regression**:  It an appropriate choice for predicting stroke likelihood (0 if no stroke, 1 if stroke).

**Random Forest**:  Multiple decision trees to improve predictive performance. Given the variety of attributes in the dataset and the potential non-linear relationships between predictors and stroke likelihood.

Please assign me this issue under label GSSOC'24.
Looking forward to contribute in this project!

Best Regards,
Divyanshi
GSSOC'24 contributor

**Comment by SrijanShovit** [comment]
Hi @Divyanshi1002 Good to see your spirits. However, have a thought if direct application of LR or RF is right or not on dataset. Will list detailed issues and then assign in the evening.

**Comment by Divyanshi1002** [comment]
hey @SrijanShovit ,
we can use SMOTE to balance the dataset by having a baseline first, then start RF and LR model on dataset.

**Comment by SrijanShovit** [comment]
Yes @Divyanshi1002 but investigation of data is also important
SMOTE you pointed out is good🤞

**Comment by Divyanshi1002** [comment]
Hi @SrijanShovit ,

Thanks for your feedback! I understand the importance of data exploration before applying models directly.

I'd be happy to investigate the dataset for potential issues like imbalance or non-linear relationships before diving into  LR and RF.

Please assign me this issue under GSSOC'24 label so I can proceed further.

**Comment by SrijanShovit** [comment]
i will open up several issues for this project for step-wise procedure and assign you there.

**Comment by Divyanshi1002** [comment]
> i will open up several issues for this project for step-wise procedure and assign you there.

Okay, sure Sir

**Comment by SrijanShovit** [comment]
No Sir😬
Proceed here: https://github.com/SrijanShovit/HealthLearning/issues/16
