### ISSUE TITLE
Cardiovascular Heart Disease | Performing Imputer of null value and Normalization of data set and EDA.

### ISSUE THREAD

**Issue by akv2011** [SrijanShovit/HealthLearning#44]
Hi I would  like to transform the data to set to be fit for model trainnig this include detection removing outilers ,filling  null value ,Normalization 

can you assign me the issue

**Comment by SrijanShovit** [comment]
First finish the task assigned then create the PR. I will assign these things eventually.

**Comment by akv2011** [comment]
HI sir  @SrijanShovit  Can you clarify Please if i Should further work on this issue (If you choose to assign me will deliver the deliverables)...Or Apply for some other issue ?

Thank You,

**Comment by SrijanShovit** [comment]
You can search for some other disease which is not being worked upon here, you can introduce yours.

**Comment by SrijanShovit** [comment]
I will come back to this issue after some days when it's appropriate.

**Comment by akv2011** [comment]
> I will come back to this issue after some days when it's appropriate.

Ok Thanks for replying will work on another disease ...if possible assign me when you come back to it will on it .

**Comment by SrijanShovit** [comment]
Yeah that's why I have not approved issue. Some things are aligned already.
