### ISSUE TITLE
Lung Cancer Detection | 2. EDA 

### ISSUE THREAD

**Issue by Dharanilakkireddy** [SrijanShovit/HealthLearning#45]
Hi @SrijanShovit ,
I would like to perform EDA on Lung Cancer Detection which includes detecting outliers, handling null values.
Could you assign me this issue.

**Comment by hit-haa18** [comment]
Hi @SrijanShovit 
I would like to contribute to this issue as well could you please assign me this

**Comment by SrijanShovit** [comment]
> Hi @SrijanShovit , I would like to perform EDA on Lung Cancer Detection which includes detecting outliers, handling null values. Could you assign me this issue.

Ok proceed with EDA. For reference, you can check other issues of EDA what's needed.

**Comment by Dharanilakkireddy** [comment]
> > Hi @SrijanShovit , I would like to perform EDA on Lung Cancer Detection which includes detecting outliers, handling null values. Could you assign me this issue.
> 
> Ok proceed with EDA. For reference, you can check other issues of EDA what's needed.

Okay!

**Comment by SrijanShovit** [comment]
@Dharanilakkireddy What's the progress?

**Comment by Dharanilakkireddy** [comment]
@SrijanShovit I'm a beginner to git, encountered with some issues I'll send the PR by tonight
