### ISSUE TITLE
Metabolic Syndrome Prediction | 1. Dataset Exploration

### ISSUE THREAD

**Issue by Arihant-Bhandari** [SrijanShovit/HealthLearning#5]
HI, im one of the contributors under GSSoC'24 and wanted to work on the stated problem statement. i would be working on basic Exploratory Data Analysis as well as modelling : i would be implementing traditional as well as gradient boosting algorithms, submitting a report on metrics as well as commenting information and segmenting sections in the work file.

i hope i can be assigned this.

**Comment by SrijanShovit** [comment]
Hey @Arihant-Bhandari , you can proceed with basic data visualization but I would publish issues properly till tonight. Will assign you that.

**Comment by Arihant-Bhandari** [comment]
thanks for the oppurtunity, will have a go at it.

**Comment by SrijanShovit** [comment]
Hi @Arihant-Bhandari Start here:

**Step 1**

1. Load the dataset
2. Explore and confirm features and label(s) of this dataset
3. Explore size/shape of dataset
4. Investigate data type of features and labels and chose any better option for a particular column for data type if possible
5. Calculate the memory usage differences
6. Explore the statistical facts like mean, median, x percentiles of the columns
