### ISSUE TITLE
Diabetes Prediction | EDA

### ISSUE THREAD

**Issue by hit-haa18** [SrijanShovit/HealthLearning#50]
Hi @SrijanShovit 
I would like to perform EDA on Diabetes Prediction dataset under GSSOC'24 
Could you please assign me this

**Comment by SrijanShovit** [comment]
@hit-haa18  Proceed.

**Comment by hit-haa18** [comment]
> @hit-haa18  Proceed.

Thankyou!!

**Comment by SrijanShovit** [comment]
@hit-haa18  any progress?

**Comment by hit-haa18** [comment]
I will send a pull request by end of today if that's ok?
I'm new to GitHub so just figuring out some things

**Comment by SrijanShovit** [comment]
> I will send a pull request by end of today if that's ok? I'm new to GitHub so just figuring out some things

Fine

**Comment by hit-haa18** [comment]
> Fine

Thank you

**Comment by hit-haa18** [comment]
> > I will send a pull request by end of today if that's ok? I'm new to GitHub so just figuring out some things
> 
> Fine

I've submitted a pull request for this issue 
Can u review it and let me know if it's proper or if there are any changes

**Comment by hit-haa18** [comment]
@SrijanShovit can you review the pr and provide your feedback

**Comment by SrijanShovit** [comment]
put it in proper folder.

**Comment by hit-haa18** [comment]
> put it in proper folder.

it is in a notebook .ipynb file 
what kind of file should I use?

**Comment by Saketh1714** [comment]
Hello Good evening @SrijanShovit can you assign this issue to me, i would like to perform EDA on diabetes prediction dataset.

**Comment by hit-haa18** [comment]
> > put it in proper folder.
> 
> it is in a notebook .ipynb file what kind of file should I use?

@SrijanShovit

**Comment by TanishChandak** [comment]
I'm excited to dive into some exploratory data analysis on the Diabetes Prediction dataset as part of GSSOC'24. I am looking forward to uncovering insights!
