### ISSUE TITLE
Metabolic Syndrome Prediction | 3. Statistical Tests for Feature Importance

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#52]
Explore 3-4 tests like PCA, chi2, anova, Permutation related tests. @Arihant-Bhandari

**Comment by codebreaker3008** [comment]
@SrijanShovit  could you assign this to me ??

**Comment by SrijanShovit** [comment]
> @SrijanShovit could you assign this to me ??

No. You can search for some disease which is not being worked upon here, you can introduce yours.

**Comment by Arihant-Bhandari** [comment]
Hi @SrijanShovit , this issue hasnt been closed yet, pls do and if possible assign the next issue as well, i have completed it as such based on what you told me in the PR
