### ISSUE TITLE
Cardiovascular Heart Disease Prediction | 2. EDA

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#53]
**Step 2:**

1. Perform Univariate and Multivariate analysis and draw conclusions from there.
2. Explore Correlation Matrix(can try different methods and search if they give the same conclusion and why)
3. Check the distribution(skewness) of the columns
4. Detect Outliers(don't remove)
5. Detect Class Label Imbalance

Provide as much relevant graphs and conclusive markdown cells as possible.

@deedGhost Please proceed with this as Step 1 is done.

**Comment by deedGhost** [comment]
@SrijanShovit yessir, I'm on it.
