### ISSUE TITLE
Endometriral Cancer Prediction | 1. Explore Dataset & 2. EDA

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#54]
Explore the dataset: https://www.kaggle.com/datasets/yeganehbavafa/uterine-corpus-endometrial-carcinoma

@RutikaW1155

Do check how other 1. Explore Dataset & 2. EDA issues need the insights. Make sure to add readme and files in separate folder.

**Comment by akv2011** [comment]
HI @SrijanShovit I would like To proceed on this issue !

For EDA Insights you Would like me to Only highlight the issue or Also solve them ?

**Comment by RutikaW1155** [comment]
Hi, @SrijanShovit I would like to proceed with this issue.
Please assign it to me, I will do my best to solve it.

**Comment by SrijanShovit** [comment]
Go ahead @RutikaW1155

**Comment by RutikaW1155** [comment]
Thank you.

**Comment by DeepikaMunimadagu** [comment]
I would like to work on this issue. Please assign it to me

**Comment by DeepikaMunimadagu** [comment]
Hi @SrijanShovit I would like to work on this issue. Please assign it to me.
