### ISSUE TITLE
Cirrhosis Prediction | 2. EDA

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#57]
**Step 2:**

1. Perform Univariate and Multivariate analysis and draw conclusions from there.
2. Explore Correlation Matrix(can try different methods and search if they give the same conclusion and why)
3. Check the distribution(skewness) of the columns
4. Detect Outliers(don't remove)
5. Detect Class Label Imbalance

Provide as much relevant graphs and conclusive markdown cells as possible.

@aditi1807

**Comment by aditi1807** [comment]
hey @SrijanShovit ,
Do i have to perform univariate analysis on the stage column

**Comment by SrijanShovit** [comment]
No not just one column. Explore all columns whatever conclusion you can bring up in the data, that's good
