### ISSUE TITLE
Stroke Prediction

### ISSUE THREAD

**Issue by Sayeda-fatima** [SrijanShovit/HealthLearning#58]
I would like to use a few classification models like decision tree, xgboost, random forest for stroke detection. Please assign me the issue. I'm a GSSoC'24 Contributor

**Comment by KunalSharma2001** [comment]
Hey,
I would like to start working on this domain to classify models like Decision Treem XGBoost, and Random Forest for Stroke Detection. It would be great if you please assign me this task.

**Comment by Mehaksaini2808** [comment]
🔴 Project Title : Stroke Prediction

🔴 Aim : To predict the chances of Stroke based on various factors

🔴 Dataset: https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset

🔴 Approach: Using logistic regression, classifiers, random forest, and decision tree for stroke detection. Comparing and listing model that produces the highest accuracy.


What is your participant role? (Mention the Open Source program)Contributor in GSSOC'24

**Comment by Saketh1714** [comment]
Hello @Mehaksaini2808 I would like to use logistic regression or random forest and knn algorithm for achieving high accuracy so i would like assign this issue to me under GSSOC'24.
