### ISSUE TITLE
Lung Cancer Detection | 1. Dataset Exploration

### ISSUE THREAD

**Issue by avii-07** [SrijanShovit/HealthLearning#6]
Hello @SrijanShovit 
I am one of the contributors to GSSOC'24. I would like to contribute to the Lung Cancer Detection project by doing EDA and then making ML models for the prediction.  I will be using matplotlib and plotly for the analysis, and for modelling I will be using algorithms like LR, RF , XGBClassifier. 

Hoping to get a positive response.

Thank you

**Comment by Piyushseth55** [comment]
Hii @SrijanShovit, I am Piyush. Under GSSOC'24, I would like to work on this issue. Please assign me this!! #gssoc24

**Comment by SrijanShovit** [comment]
@avii-07   Start here:

**Step 1**

1. Load the dataset
2. Explore and confirm features and label(s) of this dataset
3. Explore size/shape of dataset
4. Investigate data type of features and labels and chose any better option for a particular column for data type if possible
5. Calculate the memory usage differences
6. Explore the statistical facts like mean, median, x percentiles of the columns

**Comment by avii-07** [comment]
@SrijanShovit 
Thank you for assigning me this issue.

**Comment by Pookie-n-Rookie** [comment]
Hi @SrijanShovit  I want to contribute and do data exploration using various features and apply ml model for correct predictions. kindly assign me the issue
