### ISSUE TITLE
PCOS Detection | 2. EDA

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#65]
### Is your feature request related to a problem? Please describe.

PCOS Detection EDA to investigate data and generate insights.

### Describe the solution you'd like

**Step 2:**

1. Perform Univariate and Multivariate analysis and draw conclusions from there.
2. Explore Correlation Matrix(can try different methods and search if they give the same conclusion and why)
3. Check the distribution(skewness) of the columns
4. Detect Outliers(don't remove)
5. Detect Class Label Imbalance

Provide as much relevant graphs and conclusive markdown cells as possible.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oj1o1** [comment]
hey @SrijanShovit I would like to work on this issue ...Can you please assign me ?

**Comment by RutikaW1155** [comment]
Hello  @SrijanShovit , I am GSSOC'24 contributor. I have resolved a similar issue earlier and I know how to work with such an issue. Can you please assign this issue?

**Comment by bhumirao** [comment]
Hi @SrijanShovit  , i would be glad if you assign me this issue, i have previously worked in PCOS detection in my college minor project and have some meaningful insights from there, for this project . I would request you to assign me the EDA for this project, i.e dataset exploaration . I am a pre final yr student pursuining my Btech in datascience and AI ,am also a GSSOC'24 contributor .

**Comment by me-shweta** [comment]
@SrijanShovit I've reviewed the PCOS file and noticed that the dataset provides a comprehensive overview of patient demographics and medical history. I have several ideas for data visualization and to analyze relationships between the columns. I would love to contribute to this project.

**Comment by Saketh1714** [comment]
Hello @SrijanShovit can you assign this issue to me under GSSOC'24.

**Comment by pranjalipilankar** [comment]
Hello @SrijanShovit,
I would like to perform EDA on the PCOS Detection dataset under GSSOC'24. I have experience with Data Preprocessing (including PCA) and am familiar with the libraries used. 

Could you please assign me this issue.

**Comment by a-di-ti** [comment]
Hi, this is an interesting project I'd like to work on. I have similar experience with other medical image datasets and am a GSSOC '24 contributor. Looking forward to being assigned this issue!

**Comment by SrijanShovit** [comment]
any updates @Piyushseth55

**Comment by me-shweta** [comment]
@SrijanShovit I'm interested in this work. Assign me this task. :)

**Comment by JyotikaJayani-08** [comment]
Please assign me this issue .

**Comment by Piyushseth55** [comment]
> any updates @Piyushseth55

Task completed. Make the PR, please check it. Please assigne this issue to me.

**Comment by Taranpreet10451** [comment]
@SrijanShovit I am good at it please assign this to me.

**Comment by Piyushseth55** [comment]
> PCOS Detection EDA to investigate data and generate insights.

correct the file name and make the PR, please check it.

**Comment by Ar7109** [comment]
@SrijanShovit I have worked earlier in machine learning field. Please assign to me under gssoc 2024
