### ISSUE TITLE
Body Fat Prediction | 3. Feature Importance | 3.3 ML Based Feature Importance Tests

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#66]
### Is your feature request related to a problem? Please describe.

Related to highlighting features importance in this dataset.

### Describe the solution you'd like

Explore techniques like RFE, DT and others (at least 5).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SrijanShovit** [comment]
@MehekFatima  proceed here

**Comment by MehekFatima** [comment]
okay @SrijanShovit

**Comment by MehekFatima** [comment]
can you please describe more about my task? how should I proceed. 
@SrijanShovit

**Comment by SrijanShovit** [comment]
Nope, explore DT, RFE, RF, XGB which apart from prediction are also used to find feature importance. Read about them and then the code part(no prediction)

**Comment by MehekFatima** [comment]
Okay 👍 got it

**Comment by Pranali3103** [comment]
Hi @SrijanShovit please assign me this issue , I am GSSOC'24 contributor

**Comment by SrijanShovit** [comment]
> Okay 👍 got it

Any progress?
