### ISSUE TITLE
Contributors Highlight

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#67]
### Is your feature request related to a problem? Please describe.

To highlight handles of contributors

### Describe the solution you'd like

Script that picks the contributors from repo and fetches their linkedin, twitter, github profiles and displays in tabular form.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anmantout** [comment]
Hello, I would like to work on this issue. Can you please assign it to me? Thanks!

**Comment by SrijanShovit** [comment]
Go ahead @anmantout

**Comment by SrijanShovit** [comment]
what's the progress @anmantout

**Comment by SrijanShovit** [comment]
Closing as no updates
