### ISSUE TITLE
Diabetes Classification | 1. Dataset Exploration

### ISSUE THREAD

**Issue by Anuragsarkar12** [SrijanShovit/HealthLearning#7]
Hey @SrijanShovit 
I am Anurag , I am contributor in GSSoC'24 . I am exploring machine learning and would like to work on the diabetes classification dataset.
My  Approach:
I would begin my process by creating in-depth plots between the several features of a diagnosis to predict which parameters are relevant to the diagnosis. Based on my deductions I would use the chosen parameters to create a classification model using either Logistic Regression or Random Forest Classifier, making changes if necessary along the way.
I hope you find my approach useful and assign me this project under GSSoC'24.

Thank You,
Anurag

**Comment by SrijanShovit** [comment]
@Anuragsarkar12 , Start here:

**Step 1**

1. Load the dataset
2. Explore and confirm features and label(s) of this dataset
3. Explore size/shape of dataset
4. Investigate data type of features and labels and chose any better option for a particular column for data type if possible
5. Calculate the memory usage differences
6. Explore the statistical facts like mean, median, x percentiles of the columns

**Comment by Anuragsarkar12** [comment]
Hey @SrijanShovit, I am not able to understand, what you mean by 'Calculate the memory usage differences', do you mean the memory difference between the original dataset and the one that i create after making appropriate changes?

**Comment by Anuragsarkar12** [comment]
I have created a pull request , please do tell me if any changes are required

**Comment by SrijanShovit** [comment]
Calculate the memory usage differences; In case you chose to change data type of a column that is unnecessarily into a bigger size, then this would make sense to you.

**Comment by SrijanShovit** [comment]
Rest of things are fine in the PR.

**Comment by Anuragsarkar12** [comment]
Yeah, I changed the data type of BMI from integer to float and noticed the difference in memory usage, I think I have completed the tasks in dataset exploration, what should do now? Should I build the model?

**Comment by Anuragsarkar12** [comment]
I made some updates in my file, but I am not able to find a way to update it in my forked repository, can you please help me?

**Comment by SrijanShovit** [comment]
> I made some updates in my file, but I am not able to find a way to update it in my forked repository, can you please help me?

What's the actual issue?

**Comment by Anuragsarkar12** [comment]
I though of performing EDA on the dataset, I just saw that it has been
assigned to someone else

**Comment by SrijanShovit** [comment]
It's ok; proceed with Feature Importance.

**Comment by Anuragsarkar12** [comment]
Okk
