### ISSUE TITLE
Breast Cancer | 3. Statistical Feature Importance

### ISSUE THREAD

**Issue by SrijanShovit** [SrijanShovit/HealthLearning#75]
### Is your feature request related to a problem? Please describe.

Feature importance

### Describe the solution you'd like

Statistical Methods

### Describe alternatives you've considered

@vedanshipathak Proceed here.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sravaniyaramasu** [comment]
@SrijanShovit I would love to work on this. Please assign it to me

**Comment by yusuf-khaan** [comment]
@SrijanShovit I would be glad to be a part of this can you assign me this issue

**Comment by vedanshipathak** [comment]
@SrijanShovit can you please elaborate me a little on this ,like should i go with preprocessing(standardizing ) the data and then applying the ML model ? or something else .

**Comment by SrijanShovit** [comment]
> @SrijanShovit can you please elaborate me a little on this ,like should i go with preprocessing(standardizing ) the data and then applying the ML model ? or something else .

Nope this will be a later step .Look for feature importance in ML. What are its types and algorithms. You might find terms like Feature Selection or Extraction.
