### ISSUE TITLE
Infant Health | EDA

### ISSUE THREAD

**Issue by Vedantkoppal** [SrijanShovit/HealthLearning#76]
**Is your feature request related to a problem? Please describe.**

**Perform EDA on the Infant Health Dataset**
The data of infant health is ready and i would like to perform EDA on it.

**Details**
Perform univariate and multivariate analysis, outlier detection and possibly removal if you allow and other all standard EDA processes.
Feature selection.
Feature extraction - Will try to create new features for best accuracy

I also want to train a ML and DL algo using Linear Regression, Decision Tree, XG Boost, and neural network.

Compare all the models and determine which model will perform best with particular data

I am GSSOC contributor.

**Comment by SrijanShovit** [comment]
Already worked upon. Please check or ask me before opening an issue.

**Comment by Vedantkoppal** [comment]
Okay 
What about Hepatitis C ?!
Its not showing any data in its folder.
I have found a similar dataset on kaggle here:

https://www.kaggle.com/datasets/fedesoriano/hepatitis-c-dataset

I can perform all techniques that mentioned above  on this dataset.
 
Can i work on that then?

**Comment by Vedantkoppal** [comment]
@SrijanShovit

**Comment by SrijanShovit** [comment]
Check if it is same or diff dataset as per this repo?
