### ISSUE TITLE
Liver Disease Prediction | Dataset Exploration and EDA

### ISSUE THREAD

**Issue by W-ight** [SrijanShovit/HealthLearning#78]
**Is your feature request related to a problem? Please describe.**
An model which predict whether a patient is a liver patient or not, based on various parameters is also an issue for Health Learning 

**Describe the solution you'd like**
I want to add a ML Liver Disease prediction model which can classify if a person is liver patient or not up to an accuracy.

@SrijanShovit I would like to work on this. Please assign it to me under gssoc24

**Comment by SrijanShovit** [comment]
Which dataset? @W-ight

**Comment by W-ight** [comment]
There is a dataset name Indian Liver Patient Records in Kaggle I can use that. Or if you have any other idea for dataset i am open to that also @SirjanShovit

**Comment by SrijanShovit** [comment]
Ok proceed with Dataset exploration and EDA. For reference, you can find other #1. and #2. Issues

**Comment by W-ight** [comment]
Thanks. I will start working on it

**Comment by SrijanShovit** [comment]
Re opening or any one to take it up

**Comment by Sayeda-fatima** [comment]
@SrijanShovit I would like to work on this issue. Please assign it to me. I'm a GSSoC'24 contributor

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.

**Comment by Sayantan-Karmakar** [comment]
**I would like to complete the prediction model using Indian liver patient records from kaggle. **
Link : https://www.kaggle.com/datasets/uciml/indian-liver-patient-records
Kindly assign me this.
