### ISSUE TITLE
Heart Attack Prediction | Dataset Exploration and EDA

### ISSUE THREAD

**Issue by jain-anshika** [SrijanShovit/HealthLearning#79]
# Heart Attack Prediction Model

## Predict if a person is prone to a heart attack or not.

We can add heart attack prediction model which predicts the chances of heart attack based on various factors:-
- Age of the patient
- Sex of the patient 
- Chest pain type
- Resting blood pressure (in mm Hg)
- Cholestoral in mg/dl fetched via BMI sensor
- Fasting blood sugar
- Resting electrocardiographic
- Maximum heart rate achieved
- Previous peak
- Slope
- Number of major vessels
- Thalium Stress Test result
- Exercise induced angina
- Target variable

Please assign this issue to me under GSSoC'24. I would like to work on this model.

**Comment by SrijanShovit** [comment]
Go ahead @jain-anshika 
Add proper folder and readme.
You can check the code in Metabolic syndrome folder what all I expect in EDA.

**Comment by Teja-m9** [comment]
hey @SrijanShovit as i already do some projects on machine learning and i am familiar with the dl also.
As i can do so many predictive models and pls assign this to me .
I really love to work under GSSOC'24 .
As i beleive that it would help me to acheive my  skills.

**Comment by jain-anshika** [comment]
@Teja-m9  I am already done with this issue and my PR is about to be merged.

**Comment by SrijanShovit** [comment]
> hey @SrijanShovit as i already do some projects on machine learning and i am familiar with the dl also. As i can do so many predictive models and pls assign this to me . I really love to work under GSSOC'24 . As i beleive that it would help me to acheive my skills.

It's already assigned to someone else.
