### ISSUE TITLE
Breast Cancer | Dataset Exploration and EDA

### ISSUE THREAD

**Issue by sanskritilabroo** [SrijanShovit/HealthLearning#80]
### Is your feature request related to a problem? Please describe.

No ML Algorithm is applied in the breast cancer problem. I can apply logistic regression. Please assign me this as a contributor under GSSOC'24.

### Describe the solution you'd like

Applying logistic regression model for classification of breast cancer malignant and normal blood cells.
Also showcase results through accuracy metrics and visualization techniques.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SrijanShovit** [comment]
I have some things already in line. You can suggest some new disease or topic. I shall approve it.
