### ISSUE TITLE
Thyroid Analysis 

### ISSUE THREAD

**Issue by PriyankaRaskhit** [SrijanShovit/HealthLearning#86]
### Is your feature request related to a problem? Please describe.

I would like to do Thyroid Data Analysis by performing EDA and with XGBoost. 

### Describe the solution you'd like

To find the no. of patients who have revived from thyroid cancer and the patients with recurred cancer

### Describe alternatives you've considered

Prediction with Linear Regression, Random Forest and Decision Tree 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SrijanShovit** [comment]
dataset link?

**Comment by SrijanShovit** [comment]
Any progress? @PriyankaRaskhit

**Comment by PriyankaRaskhit** [comment]
It is a UCI Machine Learning Repository dataset ma'am 
LINK: https://archive.ics.uci.edu/dataset/915/differentiated+thyroid+cancer+recurrence
