### ISSUE TITLE
Cardiovascular Heart Disease Prediction | 1. Dataset Exploration

### ISSUE THREAD

**Issue by deedGhost** [SrijanShovit/HealthLearning#9]
Hey @SrijanShovit 
I would like to contribute for the project Cardiovascular Heart Disease as GSSOC'24 contributor by implementing the KNN and SVM models on the given dataset.
Thank you.

**Comment by Basma2423** [comment]
I'd very much like to work on this, can you assign it to me, please? @SrijanShovit 

Full name: **Basma Mahmoud**
GitHub Profile Link: [Basma2423](https://github.com/Basma2423)
Email ID: mayarbasma2423@gmail.com
Approach for this Project:
If CV: Multiple Deep Learning pre-trained models + CNN
else: build models with different DL architectures and pick the one with higher accuracy (or use other simpler algorithms depending on the dataset)
What is your participant role? (Mention the Open Source program): **GSSoC-2024** participant

Can you add the label for GSSoC, please?
Thanks.

**Comment by SrijanShovit** [comment]
Hi @deedGhost  Start here:

**Step 1**

1. Load the dataset
2. Explore and confirm features and label(s) of this dataset
3. Explore size/shape of dataset
4. Investigate data type of features and labels and chose any better option for a particular column for data type if possible
5. Calculate the memory usage differences
6. Explore the statistical facts like mean, median, x percentiles of the columns

**Comment by deedGhost** [comment]
Hey @SrijanShovit . 
Sorry I am unable to add the file at correct place, can u please help me in this...
