### ISSUE TITLE
TRAINING ON CNN  and other DL Algo | Acne_Prediction | Step-2

### ISSUE THREAD

**Issue by Saksh8** [SrijanShovit/HealthLearning#91]
As per our discussion step 1 of building a data  input pipe line and pre procession part is done.So here I'm moving to the next of Model Training. Kindly assign me with one.

**Comment by SrijanShovit** [comment]
Would like you to go through these things as mentioned here in the discussion with Shruti
https://github.com/SrijanShovit/HealthLearning/pull/56
