### ISSUE TITLE
Lung Cancer Detection| ML and Statistics based Feature Importance 

### ISSUE THREAD

**Issue by avii-07** [SrijanShovit/HealthLearning#93]
Methods used : 

Random forest
Decision Trees
XGBoost
RFE

Chi-Square test
Anova test

**Comment by SrijanShovit** [comment]
> Methods used :
> 
> Random forest Decision Trees XGBoost RFE
> 
> Chi-Square test Anova test

Nope not only this:
once go through https://github.com/SrijanShovit/HealthLearning/blob/main/Metabolic%20Syndrome%20Prediction/metabolic_syndrome_predict.ipynb

**Comment by SrijanShovit** [comment]
@avii-07 contact me on discord once.

**Comment by avii-07** [comment]
@SrijanShovit 
I have texted you on discord under Text channel .

**Comment by avii-07** [comment]
@SrijanShovit 
I have replied to you on the discord. Kindly look into it.

Also please tell me the steps of this feature importance issue.

**Comment by SrijanShovit** [comment]
@avii-07 You can explore code of @Arihant-Bhandari under Metabolic Syndrome for this.
