### ISSUE TITLE
Add "Angiographic coronary heart disease "classification model.

### ISSUE THREAD

**Issue by kRiShNa-429407** [SrijanShovit/HealthLearning#95]
### Is your feature request related to a problem? Please describe.

This model takes various [Parameters](![Screenshot 2024-05-18 132640](https://github.com/SrijanShovit/HealthLearning/assets/131583096/c1c44048-7bb1-4659-a3e5-d2af4625a49e)) like age , cholesterol, etc, to predict the heart disease (target)

### Describe the solution you'd like

To train this model I used various classification machine learning algorithms like KNN , Random Forest  , Logistic Regression.
The RandomForest gives me score of 0.885 with tunned hyperparameters.
![Screenshot 2024-05-18 133018](https://github.com/SrijanShovit/HealthLearning/assets/131583096/eadf7d34-4965-45b2-8498-f436f9253f5f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SrijanShovit** [comment]
Dataset link?

**Comment by kRiShNa-429407** [comment]
Okk wait

**Comment by kRiShNa-429407** [comment]
The original set comes from the UCI Machine Learning Repository

https://archive.ics.uci.edu/dataset/45/heart+disease

**Comment by SrijanShovit** [comment]
but you see it's same is what's going in one of the projects, if you didn't explore.

**Comment by SrijanShovit** [comment]
> but you see it's same is what's going in one of the projects, if you didn't explore.

Need not have a separate issue about it.

**Comment by kRiShNa-429407** [comment]
okk
