### ISSUE TITLE
Brain Tumor MRI Classification | Step 2

### ISSUE THREAD

**Issue by theiturhs** [SrijanShovit/HealthLearning#96]
### Is your feature request related to a problem? Please describe.

We have completed data exploration and augmentation. In this I would like to proceed with choosing best cross validation technique and choosing the model.

### Describe the solution you'd like

This will be the procedure

Choosing Cross Validation technique (sklearn library)

* Stratified K-Fold,
* K-Fold
* Repeated K-Fold
* LOOCV

Model Selection

* Simple CNN architecture
* FastAI architecture (VGG, ResNet)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SrijanShovit** [comment]
@theiturhs proceed
